// <auto-generated />
using System;
using Hitsounder.Game.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hitsounder.Game.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522113556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Hitsounder.Game.Core.ProjectInfo", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeatmapPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeatmapSetPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
